#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Auto-converted from Jupyter notebook: transact_replicate.ipynb
# Generated by ChatGPT on conversion request.
# Notes:
# - IPython/Jupyter magics (%, %%, get_ipython) and shell commands (!...) were removed or commented.
# - Markdown cells were converted into comments to preserve context.
# - If the notebook relied on environment setup (e.g., pip installs, %cd), ensure your environment is prepared.

########################################################################################
# Importing necessary libraries
########################################################################################

# %% [code] cell 2

import tarfile
import os

import pandas as pd, numpy as np, gc
from pathlib import Path
from collections import defaultdict, Counter, deque


import  glob

from dataclasses import dataclass


# Core libs
import logging
import random

# PyTorch
import torch
import torch.nn as nn

# Typing
from typing import Final

from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

import math, copy

# %% [code] cell 3

# Define paths
tar_file_path = '/home/p_esla/Downloads/aliccp-sample_train.tar.gz' # Example path
extraction_path = '/home/p_esla/Downloads/ali-ccp-extracted'

# Define path for test file
test_file_path = '/home/p_esla/Downloads/sample_test.tar.gz'

# Create extraction directory
print(f"Contents extracted to: {extraction_path}")

# %% [code] cell 4
# ========= Stream-build ready_seq.train.csv from sample_skeleton (memory safe) =========

SKELETON = Path("/home/p_esla/Downloads/ali-ccp-extracted/sample_skeleton_train.csv")  # <- your path
OUT_DIR  = Path("/home/p_esla/Downloads/ali-ccp/work"); OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_CSV  = OUT_DIR / "ready_seq.train.csv"
MAP_UCSV = OUT_DIR / "uid_map.csv"
MAP_ICSV = OUT_DIR / "iid_map.csv"

assert SKELETON.exists(), f"Missing: {SKELETON}"

# We only need: clk (col 0), user hash (col 3), adgroup_id (col 4)
USECOLS = [0, 3, 4]
NAMES   = ["clk", "user_raw", "adgroup_id"]

# Dictionaries we grow as we stream:
user_map    = {}                 # raw user -> contiguous u
item_map    = {}                 # adgroup_id -> contiguous i
user_offset = defaultdict(int)   # running count (for time_stamp) per u
next_u = 0
next_i = 0

# Initialize output with header
with open(OUT_CSV, "w") as f:
    f.write("u,i,time_stamp,clk\n")

CHUNK = 500_000  # tune for your RAM/IO; 200k–1M is typical

reader = pd.read_csv(
    SKELETON,
    header=None,
    usecols=USECOLS,
    names=NAMES,
    dtype={0: "object", 3: "object", 4: "object"},
    chunksize=CHUNK,
    low_memory=True
)

total_rows = 0
for ci, chunk in enumerate(reader, 1):
    # 1) Coerce types & binarize label
    chunk["clk"] = pd.to_numeric(chunk["clk"], errors="coerce").fillna(0).astype(np.int64)
    chunk["clk"] = (chunk["clk"] > 0).astype("int8")

    # 2) Map user_raw -> contiguous u (vectorized)
    new_users = pd.Index(chunk["user_raw"].unique()).difference(user_map.keys())
    if len(new_users):
        add = {u: (next_u + k) for k, u in enumerate(new_users)}
        user_map.update(add)
        next_u += len(add)
    chunk["u"] = chunk["user_raw"].map(user_map).astype("int64")

    # 3) Map adgroup_id -> contiguous i (vectorized)
    chunk["adgroup_id"] = pd.to_numeric(chunk["adgroup_id"], errors="coerce")
    chunk = chunk.dropna(subset=["adgroup_id"])
    chunk["adgroup_id"] = chunk["adgroup_id"].astype("int64")

    new_items = pd.Index(chunk["adgroup_id"].unique()).difference(item_map.keys())
    if len(new_items):
        add = {int(v): (next_i + k) for k, v in enumerate(new_items)}
        item_map.update(add)
        next_i += len(add)
    chunk["i"] = chunk["adgroup_id"].map(item_map).astype("int64")

    # 4) Monotonic per-user time_stamp = previous_count[u] + within-chunk cumcount
    #    (preserves file order; no global sort needed)
    chunk["ts_local"] = chunk.groupby("u").cumcount().astype("int64")
    # map current offsets
    chunk["ts_offset"] = chunk["u"].map(user_offset).astype("int64")
    chunk["time_stamp"] = chunk["ts_offset"] + chunk["ts_local"]

    # update offsets for next chunk
    counts = chunk["u"].value_counts()
    for u, c in counts.items():
        user_offset[int(u)] += int(c)

    # 5) Keep only minimal columns and write append-only
    out = chunk[["u", "i", "time_stamp", "clk"]].astype({"u":"int32","i":"int32","time_stamp":"int64","clk":"int8"})
    out.to_csv(OUT_CSV, mode="a", header=False, index=False)

    total_rows += len(chunk)
    del chunk, out
    gc.collect()
    if ci % 10 == 0:
        print(f"[chunk {ci}] rows processed: {total_rows:,} | users={len(user_map):,} | items={len(item_map):,}")

# Save maps (optional, useful for decoding back)
pd.DataFrame({"u": range(len(user_map)), "user_raw": pd.Index(user_map).sort_values()}).to_csv(MAP_UCSV, index=False)
pd.DataFrame({"i": range(len(item_map)), "adgroup_id": pd.Index(item_map).sort_values()}).to_csv(MAP_ICSV, index=False)

print(f"\nWrote {OUT_CSV}  | rows={total_rows:,}")
print(f"Users={len(user_map):,}  Items={len(item_map):,}")

########################################################################################
# Hyperparameters Configurations
########################################################################################

# %% [code] cell 6
# Ali-CCP column names (common defaults shown)
USER_COL = "user"
ITEM_COL = "adgroup_id"
TIME_COL = "time_stamp"   # UNIX seconds
LABEL_COL = "clk"         # 0/1

# Sequence building
SEQ_LEN = 100
MIN_CLICK_HISTORY = 1      # require at least this many prior clicks to form a history

# Data subset (set to None to use all)
MAX_ROWS = None            # e.g., 2_000_000 for dev
MAX_USERS = None           # e.g., 100_000 for dev

# DataLoader
BATCH_SIZE = 256

# Rebalancing (downsample negatives via a weighted sampler in training)
TARGET_POS_RATIO = 0.25    # ≈ 1:3 pos:neg in each batch; set to None to disable

# Will be set in Cell 2:
RAW_PATH = Path("/home/p_esla/Downloads/aliccp-sample_train.tar.gz")  # Path to /content/raw_sample.csv (or extracted file)

########################################################################################
# setup and download the dataset
########################################################################################

########################################################################################
# #  Build Ali-CCP sequential dataset + DataLoaders
########################################################################################

# %% [code] cell 10

def resolve_raw_csv(path_like, prefer_names=("raw_sample.train.csv","raw_sample.csv")) -> str:
    """Return a CSV path. If given a tar.gz or a dir, extract/locate the CSV."""
    p = Path(path_like)
    if p.is_dir():
        # Try preferred filenames first
        for nm in prefer_names:
            cp = p / nm
            if cp.exists():
                return str(cp)
        # Otherwise, any CSV inside
        cs = list(p.rglob("*.csv"))
        assert cs, f"No CSV found inside directory: {p}"
        return str(cs[0])

    # .tar.gz / .tgz: extract then locate CSV
    suff = "".join(p.suffixes[-2:]).lower()
    if suff in [".tar.gz", ".tgz"]:
        outdir = Path("/home/p_esla/Downloads/ali-ccp/auto_extract")
        outdir.mkdir(parents=True, exist_ok=True)
        with tarfile.open(p, "r:gz") as tf:
            tf.extractall(outdir)
        # Prefer raw_sample*.csv if present
        cs = sorted(list(outdir.rglob("raw_sample*.csv")))
        if not cs:
            cs = sorted(list(outdir.rglob("*.csv")))
        assert cs, f"No CSV found after extracting archive: {p}"
        return str(cs[0])

    # Otherwise assume it's already a CSV file
    assert p.suffix.lower() == ".csv", f"RAW_PATH must be a CSV (or dir/tar.gz), got: {p}"
    return str(p)


RAW_PATH = resolve_raw_csv(RAW_PATH)
print("Using CSV:", RAW_PATH)

########################################################################################
# Transact config
########################################################################################

# %% [code] cell 12

@dataclass
class TransActConfig:
    """
    Configuration class to build a TransAct PyTorch module.

    :param seq_len: Length of the input sequence
    :param time_window_ms: Time window in milliseconds for random window mask
    :param latest_n_emb: Number of latest embeddings to use in output
    :param concat_candidate_emb: Whether to concatenate candidate embeddings with user sequence
    :param concat_max_pool: Whether to apply max pooling to the output of the transformer encoder and append it to output
    :param action_vocab: Vocabulary of user actions
    :param action_emb_dim: Dimension of user action embeddings
    :param item_emb_dim: Dimension of item embeddings
    :param num_layer: Number of TransformerEncoderLayer
    :param nhead: Number of heads in the TransformerEncoderLayer
    :param dim_feedforward: Feed forward dimension of the TransformerEncoderLayer
    """

    seq_len: int = 100
    time_window_ms: int = 1000 * 60 * 60 * 1
    latest_n_emb: int = 10
    concat_candidate_emb: bool = True
    concat_max_pool: bool = True
    action_vocab: list = range(0, 20)
    action_emb_dim: int = 32
    item_emb_dim: int = 32
    num_layer: int = 2
    nhead: int = 2
    dim_feedforward: int = 32

########################################################################################
# Build the transformer(transact) network
########################################################################################

# %% [code] cell 14
class TransAct(nn.Module):
    """
    TransAct: Transformer-based Realtime User Action Model for Recommendation at Pinterest
    (Backbone; scoring head is external.)
    """

    def __init__(self, transact_config: TransActConfig):
        super().__init__()
        self.transact_config = transact_config
        self.action_emb_dim: Final[int] = self.transact_config.action_emb_dim
        self.item_emb_dim:   Final[int] = self.transact_config.item_emb_dim
        self.concat_candidate_emb: Final[bool] = self.transact_config.concat_candidate_emb
        self.time_window_ms: Final[int] = self.transact_config.time_window_ms
        self.seq_len:        Final[int] = self.transact_config.seq_len
        self.latest_n_emb:   Final[int] = self.transact_config.latest_n_emb
        self.action_vocab:   Final[list] = self.transact_config.action_vocab  # e.g., [0,1] for impr/click

        if self.concat_candidate_emb:
            transformer_in_dim = self.action_emb_dim + self.item_emb_dim * 2
        else:
            transformer_in_dim = self.action_emb_dim + self.item_emb_dim
        self.transformer_in_dim = transformer_in_dim

        # Reserve 0 for PAD; real actions map to 1..K
        self.register_buffer("action_type_lookup", self.convert_vocab_to_idx())
        self.action_emb_module = nn.Embedding(
            num_embeddings=len(self.action_vocab) + 1,  # +1 for PAD slot at 0
            embedding_dim=self.action_emb_dim,
            padding_idx=0,                               # 0 == PAD only
        )

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=transformer_in_dim,
            nhead=self.transact_config.nhead,
            dim_feedforward=self.transact_config.dim_feedforward,
            batch_first=True,
        )
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer, num_layers=self.transact_config.num_layer
        )
        if self.transact_config.concat_max_pool:
            self.out_linear = nn.Linear(transformer_in_dim, transformer_in_dim)

    def convert_vocab_to_idx(self) -> torch.Tensor:
        """
        Map raw action ids to embedding indices with PAD=0.
        Assumes input action_type_seq uses -1 for PAD, so index with (a + 1):
          -1+1 -> 0 (PAD),  0+1 -> 1 (first real action), etc.
        """
        logging.info(f"Action used: {self.action_vocab}")
        t = torch.zeros(100, dtype=torch.long)  # original size; enlarge if needed
        i = 1  # start from 1 so PAD stays 0
        for aid in sorted(self.action_vocab):
            idx = aid + 1
            if idx >= t.numel():
                t = torch.cat([t, torch.zeros(idx - t.numel() + 1, dtype=torch.long)], dim=0)
            t[idx] = i
            i += 1
        return t

    def _adjust_mask(self, pad_mask: torch.Tensor, time_mask: torch.Tensor) -> torch.Tensor:
        """
        Combine padding and time-window masks for src_key_padding_mask.
        Returns BoolTensor where True => position is ignored by attention.
        """
        mask = torch.bitwise_or(pad_mask, time_mask)
        if mask.size(1) > 0:
            mask[:, 0] = False  # ensure at least one token visible
        return mask  # BoolTensor

    def forward(
        self,
        action_type_seq: torch.Tensor,    # (B,S)  -1=PAD, 0=impr, 1=click (2=purchase if you add CVR)
        item_embedding_seq: torch.Tensor, # (B,S,D)
        action_time_seq: torch.Tensor,    # (B,S)  IMPORTANT: same units as request_time
        request_time: torch.Tensor,       # (B,1) or (B,) or (B,1,1)
        item_embedding: torch.Tensor,     # (B,D)
    ) -> torch.Tensor:

        # step 1: clip to seq_len
        action_type_seq    = action_type_seq[:, : self.seq_len]
        item_embedding_seq = item_embedding_seq[:, : self.seq_len, :]
        action_time_seq    = action_time_seq[:, : self.seq_len]

        # step 2: action embedding (PAD->0; real actions -> 1..K)
        at_idx = self.action_type_lookup[action_type_seq + 1]
        action_emb_tensor = self.action_emb_module(at_idx)  # (B,S,A)

        # step 3: key padding mask (Bool), plus time-window mask
        pad_mask = (at_idx == 0)  # True where PAD (impressions are NOT PAD)

        # normalize request_time to (B,S)
        req = request_time
        if req.dim() == 3 and req.size(-1) == 1:  # (B,1,1)->(B,1)
            req = req.squeeze(-1)
        if req.dim() == 1:                        # (B,)->(B,1)
            req = req.unsqueeze(1)
        req = req.expand(-1, self.seq_len)        # (B,1)->(B,S)

        # IMPORTANT: ensure req and action_time_seq have the SAME units (ms or sec)
        rand_time_window_ms = random.randint(0, self.time_window_ms)
        short_time_window_idx_trn  = (req - action_time_seq) < rand_time_window_ms
        short_time_window_idx_eval = (req - action_time_seq) < 0

        if self.training:
            key_padding_mask = self._adjust_mask(pad_mask, short_time_window_idx_trn)
        else:
            key_padding_mask = self._adjust_mask(pad_mask, short_time_window_idx_eval)
        # key_padding_mask is BoolTensor (True => ignore)

        # step 4: stack embeddings
        action_pin_emb = torch.cat((action_emb_tensor, item_embedding_seq), dim=2)
        if self.concat_candidate_emb:
            item_embedding_expanded = item_embedding.unsqueeze(1).expand(-1, self.seq_len, -1)
            action_pin_emb = torch.cat((action_pin_emb, item_embedding_expanded), dim=-1)

        # step 5: transformer
        tfmr_out = self.transformer_encoder(
            src=action_pin_emb,
            src_key_padding_mask=key_padding_mask  # Bool mask
        )

        # step 6: output packing
        output_concat = []
        if self.transact_config.concat_max_pool:
            pooled_out = self.out_linear(tfmr_out.max(dim=1).values)
            output_concat.append(pooled_out)
        if self.latest_n_emb > 0:
            tfmr_out = tfmr_out[:, : self.latest_n_emb]
        output_concat.append(tfmr_out.flatten(1))
        return torch.cat(output_concat, dim=1)

    @property
    def output_dim(self) -> int:
        H = self.transformer_in_dim
        N = self.transact_config.latest_n_emb if self.transact_config.latest_n_emb > 0 else self.transact_config.seq_len
        return (H if self.transact_config.concat_max_pool else 0) + N * H

########################################################################################
# Instantiating the config
########################################################################################

# %% [code] cell 16
device = "cuda" if torch.cuda.is_available() else "cpu"

# Example: adjust to your dataset
# - SEQ_LEN: whatever you used when creating sequences (e.g., 20)
# - ITEM_EMB_DIM: the dimensionality of your item embeddings/table (e.g., 64)
# - action_vocab: if you only have click, set [0,1]
cfg = TransActConfig(
    seq_len=SEQ_LEN,                # <- from your dataset pipeline
    item_emb_dim= 32,      # <- your item embedding width
    action_vocab=[0, 1],            # click-only (0=no-op id, 1=click)
    time_window_ms=60_000,          # 1 minute; match your timestamps' unit
    latest_n_emb=1,
    concat_candidate_emb=True,
    concat_max_pool=True,
    num_layer=2,
    nhead=2,
    dim_feedforward=32,
)

encoder = TransAct(cfg).to(device)
print("TransAct output_dim:", encoder.output_dim)

# %% [code] cell 17
# ---- Revised: use the streamed CSV (no remapping needed) ----

# 1) Point to the file created by the streaming prep
RAW_PATH = "/home/p_esla/Downloads/ali-ccp/work/ready_seq.train.csv"   # adjust if different
assert Path(RAW_PATH).exists(), f"Missing: {RAW_PATH}"

# 2) Sanity check schema on a tiny sample
sample = pd.read_csv(RAW_PATH, nrows=5)
assert set(sample.columns) >= {"u", "i", "time_stamp", "clk"}, f"Unexpected columns: {sample.columns.tolist()}"
print(sample.head())

# 3) Define the columns your pipeline expects
USER_COL  = "u"
ITEM_COL  = "i"
TIME_COL  = "time_stamp"
LABEL_COL = "clk"

# 4) Infer NUM_USERS / NUM_ITEMS / CTR with chunked scan (memory-safe)
NUM_USERS = -1
NUM_ITEMS = -1
NROWS = 0
POS = 0

dtypes = {"u": "int32", "i": "int32", "time_stamp": "int64", "clk": "int8"}
for ch in pd.read_csv(RAW_PATH, usecols=[USER_COL, ITEM_COL, TIME_COL, LABEL_COL],
                      dtype=dtypes, chunksize=500_000):
    if ch.empty:
        continue
    NROWS += len(ch)
    POS   += int(ch[LABEL_COL].sum())
    NUM_USERS = max(NUM_USERS, int(ch[USER_COL].max()))
    NUM_ITEMS = max(NUM_ITEMS, int(ch[ITEM_COL].max()))

NUM_USERS += 1
NUM_ITEMS += 1
CTR = POS / max(1, NROWS)

print(f"Ready → NUM_USERS={NUM_USERS:,} | NUM_ITEMS={NUM_ITEMS:,} | rows={NROWS:,} | CTR={CTR:.4f}")

# %% [code] cell 18
# ========= Streaming throttle → build a smaller subset CSV (RAM-safe) =========
# ========= Streaming throttle → build a smaller subset CSV (RAM-safe) =========

SUBSET_PATH = "/home/p_esla/Downloads/ali-ccp/work/ready_subset.csv"

MAX_USERS = 100_000
MAX_EVENTS_PER_USER = 150
MIN_CLICKS_PER_USER = 5
CHUNK = 500_000

user_col, item_col, time_col, label_col = "u", "i", "time_stamp", "clk"

# ---- Pass 1: count activity & clicks per user (no big df) ----
cnt = Counter(); clk = Counter()
for ch in pd.read_csv(RAW_PATH, usecols=[user_col, label_col],
                      dtype={user_col: "int32", label_col: "int8"},
                      chunksize=CHUNK):
    cnt.update(ch[user_col].tolist())
    clk.update(ch.loc[ch[label_col] == 1, user_col].tolist())

# Filter by clicks first, then cap by activity
active = {u for u, c in clk.items() if c >= MIN_CLICKS_PER_USER}
ranked = sorted(((u, cnt[u]) for u in active), key=lambda x: x[1], reverse=True)[:MAX_USERS]
allowed = {u for u, _ in ranked}
print(f"Selected users: {len(allowed)} (of {len(cnt)})")

if not allowed:
    raise RuntimeError("No users passed the filters; relax MAX_USERS/MIN_CLICKS_PER_USER.")

# ---- Pass 2: keep only the last MAX_EVENTS_PER_USER per allowed user ----
buffers = {u: deque(maxlen=MAX_EVENTS_PER_USER) for u in allowed}
cols = [user_col, item_col, time_col, label_col]
dtypes = {user_col: "int32", item_col: "int32", time_col: "int64", label_col: "int8"}

for ch in pd.read_csv(RAW_PATH, usecols=cols, dtype=dtypes, chunksize=CHUNK):
    ch = ch[ch[user_col].isin(allowed)]
    for row in ch.itertuples(index=False):
        buffers[getattr(row, user_col)].append(row)

# Write the subset CSV (sort by time per-user for safety)
with open(SUBSET_PATH, "w") as f:
    f.write(",".join(cols) + "\n")
    n_rows = 0
    for u, dq in buffers.items():
        rows = list(dq)
        rows.sort(key=lambda r: getattr(r, time_col))
        for r in rows:
            f.write(f"{int(getattr(r, user_col))},"
                    f"{int(getattr(r, item_col))},"
                    f"{int(getattr(r, time_col))},"
                    f"{int(getattr(r, label_col))}\n")
            n_rows += 1

print(f"Wrote subset → {SUBSET_PATH} | rows={n_rows:,} | users={len(buffers):,}")

# Point the rest of your pipeline to the smaller file
RAW_PATH = SUBSET_PATH


# ========= Item embeddings: train-or-load (feature-aware LightGCN) =========
from transact_item_no import ensure_item_model  # your single-file trainer+embedding

ITEMS_CSV     = "/home/p_esla/Downloads/ali-ccp/work/items_meta.csv"  # i + side features you prepare
ARTIFACTS_DIR = "/home/p_esla/Downloads/ali-ccp/work/artifacts"
ITEM_EMB_DIM  = encoder.transact_config.item_emb_dim  # must match cfg.item_emb_dim

# adjust to your actual item feature column names
CAT_COLS = []  # no categorical columns in items_meta.csv
NUM_COLS = ["pop_log", "ctr", "users", "recency"]  # exactly as in the CSV

item_model = ensure_item_model(
    interactions_csv=SUBSET_PATH,        # use the subset we just built (clk==1 inside)
    items_csv=ITEMS_CSV,
    artifacts_dir=ARTIFACTS_DIR,
    dim=ITEM_EMB_DIM, K=2, epochs=5,
    cat_cols=CAT_COLS, num_cols=NUM_COLS,
    device=device,
)

########################################################################################
# The added part for scoring head
########################################################################################

# %% [code] cell 20
# ========= Scoring head + item table + optimizer =========

device = "cuda" if torch.cuda.is_available() else "cpu"

# Use the same dims you set in the config
# ITEM_EMB_DIM = encoder.transact_config.item_emb_dim  # keep tied to the encoder's expectation

# Trainable item ID embedding table (ID → vector)
# item_table = nn.Embedding(NUM_ITEMS, ITEM_EMB_DIM).to(device)

# Simple CTR head: linear map over TransAct output → logit
ctr_head = nn.Linear(encoder.output_dim, 1).to(device)

# Optimizer (paper uses standard Adam-like training; tune LR as needed)
opt = torch.optim.Adam(
    list(encoder.parameters()) + list(item_model.parameters()) + list(ctr_head.parameters()),
    lr=1e-4
)

# Pointwise BCE (paper uses weighted CE with downsampling; our sampler already rebalances)
bce = nn.BCEWithLogitsLoss(reduction="mean")

# ---- Utility: pack a batch and run the model to get logits + labels ----
@torch.no_grad()
def _make_masked_seq_item_emb(seq_items_t):
    """
    seq_items_t: LongTensor (B, S), with -1 as pad
    returns: (B, S, D) masked embeddings (zeros for pad positions)
    """
    seq_items = seq_items_t.to(device)
    mask = (seq_items >= 0).unsqueeze(-1)                  # (B,S,1)
    seq_items_clamped = seq_items.clamp_min(0)             # -1 → 0 for safe index
    # seq_idx = item_model.map_raw_ids_for_seq(seq_items_clamped)
    seq_item_emb = item_model(seq_items_clamped) * mask    # zero-out pads
    return seq_item_emb

def forward_batch(batch):
    """
    Expects the Ali-CCP dataset tuple:
      seq_items_t, seq_times_t (sec), act_types_t, req_time_t (ms), cand_i_t, label_t
    Returns: logits (B,), labels (B,)
    """
    (seq_items_t, seq_times_t, act_types_t, req_time_t, cand_i_t, label_t) = batch
    B = seq_items_t.size(0)

    seq_item_emb = _make_masked_seq_item_emb(seq_items_t)              # (B,S,D)

    # Candidate item embeddings (current impression)
    cand_ids = cand_i_t.to(device).view(B)
    # cand_idx = item_model.map_raw_ids(cand_ids)

    cand_emb = item_model(cand_ids)                                    # (B,D)

    # We pass action_time in milliseconds to be consistent:
    seq_times_ms = (seq_times_t.to(device))                     # (B,S)
    req_time_ms  = req_time_t.to(device).long()                        # (B,1)

    # Action types
    act_types = act_types_t.to(device)

    # Encoder forward → representation
    enc_out = encoder(
        action_type_seq=act_types,
        item_embedding_seq=seq_item_emb,
        action_time_seq=seq_times_ms,     # already in ms
        request_time=req_time_ms,         # ms
        item_embedding=cand_emb,
    )  # (B, encoder.output_dim)

    logits = ctr_head(enc_out).squeeze(-1)                             # (B,)
    labels = label_t.to(device).squeeze(-1).float()                    # (B,)
    return logits, labels

########################################################################################
# Implementing the train loader data
########################################################################################

# %% [code] cell 22
# ---- Build TRAIN_TUPLES with minimal negatives, then reweight via TARGET_POS_RATIO ----

# 1) Load subset and sort
df = pd.read_csv(
    RAW_PATH,
    usecols=["u","i","time_stamp","clk"],
    dtype={"u":"int32","i":"int32","time_stamp":"int64","clk":"int8"}
).sort_values(["u","time_stamp"]).reset_index(drop=True)

# 2) Minimal synthetic negatives (k=1) to avoid double distribution shift
SEQ_LEN = int(getattr(encoder.transact_config, "seq_len", 100))
NUM_ITEMS = int(df["i"].max()) + 1
rng = np.random.default_rng(42)

# k = #negatives per positive (use your existing K_TRAIN / K_VAL)
def build_tuples_with_impressions(frame, k, rng, NUM_ITEMS, SEQ_LEN):
    """
    Emits 6-field tuples:
      (seq_items, seq_times_sec, seq_action_types, req_time_ms, cand_item_id, click_label)
    History contains ALL events (impressions & clicks).
    """
    samples = []
    hist = defaultdict(lambda: deque(maxlen=SEQ_LEN))  # store (item, ts_sec, action_type)

    for u, i, t, clk in frame[["u","i","time_stamp","clk"]].itertuples(index=False):
        a = 1 if int(clk) > 0 else 0   # 0=impr, 1=click
        h = hist[int(u)]

        # create a training instance only when current row is a positive (clicked)
        if len(h) >= 1 and a == 1:
            pad = SEQ_LEN - len(h)
            seq_items  = ([-1]*pad) + [it for it,_,_ in h]
            seq_times  = ([0]*pad)  + [ts for _,ts,_ in h]          # seconds here
            act_types  = ([-1]*pad) + [at for *_,at in h]           # 0/1 history

            # positive sample (clicked candidate)
            samples.append((seq_items, seq_times, act_types, int(t)*1000, int(i), 1))

            # k negatives: items not in recent history and not the positive
            excl = {it for it,_,_ in h}; excl.add(int(i))
            n = tries = 0
            while n < k and tries < k*10:
                j = int(rng.integers(0, NUM_ITEMS))
                tries += 1
                if j not in excl:
                    samples.append((seq_items, seq_times, act_types, int(t)*1000, j, 0))
                    excl.add(j); n += 1

        # ALWAYS append current exposure to history (impr or click)
        h.append((int(i), int(t), a))

    return samples

K_TRAIN = 9
TRAIN_TUPLES = build_tuples_with_impressions(df, k=K_TRAIN, rng=np.random.default_rng(42), NUM_ITEMS=NUM_ITEMS, SEQ_LEN=SEQ_LEN)

# TRAIN_TUPLES = build_tuples_with_negs_k1(df)
base_pos_rate = np.mean([t[-1] for t in TRAIN_TUPLES]) if TRAIN_TUPLES else float("nan")
print(f"TRAIN_TUPLES: {len(TRAIN_TUPLES):,}  | base_pos_rate≈{base_pos_rate:.3f} (should be ~0.5)")

# 3) (Optional) downsample for speed
# TRAIN_TUPLES = TRAIN_TUPLES[::10]

# 4) Dataset (6-field tuples → matches forward_batch)
class AliCCPSeqDataset(Dataset):
    def __init__(self, tuples): self.tuples = tuples
    def __len__(self): return len(self.tuples)
    def __getitem__(self, idx):
        seq_items, seq_times, act_types, req_ms, cand_i, y = self.tuples[idx]
        return (
            torch.tensor(seq_items, dtype=torch.long),
            torch.tensor(seq_times, dtype=torch.long),
            torch.tensor(act_types, dtype=torch.long),
            torch.tensor([req_ms], dtype=torch.long),
            torch.tensor([cand_i], dtype=torch.long),
            torch.tensor([y], dtype=torch.float32),
            )

train_ds = AliCCPSeqDataset(TRAIN_TUPLES)

labels = np.fromiter((t[-1] for t in TRAIN_TUPLES), dtype=np.int64)
q = labels.mean() + 1e-9                      # current pos rate (~0.5 with k=1)
p = float(TARGET_POS_RATIO)                   # desired pos rate
w_pos = (p / q)
w_neg = ((1 - p) / (1 - q))
weights = np.where(labels == 1, w_pos, w_neg).astype(np.float64)

# sampler = WeightedRandomSampler(weights=weights, num_samples=len(labels), replacement=True)
train_loader = DataLoader(
    train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=True,
    pin_memory=True, num_workers=2, persistent_workers=True
)

print(f"train_loader ready: {len(train_loader)} | target_pos_ratio={p:.2f}")

# %% [code] cell 23
# --- Build validation slice (last 10% per user) and loader ---

# 1) Ensure df is sorted by (u, time)
df = df.sort_values(["u", "time_stamp"]).reset_index(drop=True)

# 2) Take last 10% rows per user as validation slice
parts = []
for u, g in df.groupby("u", sort=False):
    cut = int(0.9 * len(g))
    if cut > 0:
        parts.append(g.iloc[cut:])
dfv_val = pd.concat(parts, ignore_index=True) if parts else df.iloc[0:0]
print("Validation raw rows:", len(dfv_val))

# 3) Build tuples using your existing builder (note: history is limited to the slice)
K_VAL = 5
rng_val = np.random.default_rng(123)
VALID_TUPLES = build_tuples_with_impressions(
    dfv_val, k=K_VAL, rng=rng_val, NUM_ITEMS=NUM_ITEMS, SEQ_LEN=SEQ_LEN
)
print("VALID_TUPLES:", len(VALID_TUPLES))

# 4) Loader using your existing Dataset class
valid_ds = AliCCPSeqDataset(VALID_TUPLES)
valid_loader = DataLoader(
    valid_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    pin_memory=True,
    num_workers=2,
    persistent_workers=True,
)
print("valid_loader ready:", len(valid_loader))


# 1) One epoch of train or eval (same as yours, minus HIT@3)
def run_epoch(loader, train=True):
    if train:
        encoder.train(); item_model.train(); ctr_head.train()
    else:
        encoder.eval();  item_model.eval();  ctr_head.eval()

    total_loss, total_count = 0.0, 0
    pos_sc_sum = pos_sc_n = 0.0
    neg_sc_sum = neg_sc_n = 0.0

    for batch in loader:
        logits, labels = forward_batch(batch)
        loss = bce(logits, labels)

        if train:
            opt.zero_grad()
            loss.backward()
            opt.step()

        bs = labels.numel()
        total_loss  += loss.item() * bs
        total_count += bs

        with torch.no_grad():
            probs = torch.sigmoid(logits)
            pos_mask = (labels == 1)
            neg_mask = (labels == 0)
            if pos_mask.any():
                pos_sc_sum += probs[pos_mask].sum().item()
                pos_sc_n   += pos_mask.sum().item()
            if neg_mask.any():
                neg_sc_sum += probs[neg_mask].sum().item()
                neg_sc_n   += neg_mask.sum().item()

    avg_loss = total_loss / max(1, total_count)
    pos_mean = (pos_sc_sum / max(1, pos_sc_n)) if pos_sc_n else 0.0
    neg_mean = (neg_sc_sum / max(1, neg_sc_n)) if neg_sc_n else 0.0
    return avg_loss, pos_mean, neg_mean

# 2) Validation metrics: ROC-AUC, PR-AUC, log-loss
try:
    from sklearn.metrics import roc_auc_score, average_precision_score, log_loss
except Exception:
    from sklearn.metrics import roc_auc_score, average_precision_score, log_loss

@torch.no_grad()
def evaluate_auc_logloss(loader, max_batches=None):
    encoder.eval(); item_model.eval(); ctr_head.eval()

    y_true, y_prob = [], []
    total_loss, total_count = 0.0, 0
    nb = 0

    for batch in loader:
        logits, labels = forward_batch(batch)
        probs = torch.sigmoid(logits)

        # accumulate
        y_true.append(labels.cpu().numpy().ravel())
        y_prob.append(probs.cpu().numpy().ravel())

        # loss for reference (same BCE as training)
        total_loss  += bce(logits, labels).item() * labels.numel()
        total_count += labels.numel()

        nb += 1
        if max_batches and nb >= max_batches:
            break

    if not y_true:
        return float("nan"), float("nan"), float("nan")

    y_true = np.concatenate(y_true)
    y_prob = np.concatenate(y_prob)

    # safe clipping for log_loss
    eps = 1e-7
    # force label set to avoid single-class crash
    _ = log_loss(y_true, np.clip(y_prob, eps, 1 - eps), labels=[0, 1])

    if y_true.min() == y_true.max():   # only one class present
        auc = float("nan")
        ap  = float("nan")
    else:
        auc = roc_auc_score(y_true, y_prob)
        ap  = average_precision_score(y_true, y_prob)

    val_loss = total_loss / max(1, total_count)
    return val_loss, auc, ap


# 3) Train a few epochs and report CTR metrics
EPOCHS = 50          # start small; scale up once it’s stable
MAX_EVAL_BATCHES = 100   # or set e.g. 200 if your valid set is huge to save RAM/time


ES_METRIC   = "val_loss"   # choose: "val_loss" | "roc_auc" | "pr_auc"
PATIENCE    = 5            # stop if no improvement for this many epochs
MIN_DELTA   = 1e-4         # minimum change to count as improvement

# Initialize tracking
best_val_loss = math.inf
best_auc      = -math.inf
best_pr       = -math.inf
wait = 0
best_ckpt = None

for ep in range(EPOCHS):
    tr_loss, tr_pos, tr_neg = run_epoch(train_loader, train=True)
    va_loss, va_auc, va_ap  = evaluate_auc_logloss(valid_loader, max_batches=MAX_EVAL_BATCHES)

    print(
        f"Epoch {ep+1}/{EPOCHS} | "
        f"train loss={tr_loss:.4f}  pos_prob~={tr_pos:.3f}  neg_prob~={tr_neg:.3f} || "
        f"valid loss={va_loss:.4f}  ROC-AUC={va_auc:.4f}  PR-AUC={va_ap:.4f}"
    )

    # Decide improvement based on the chosen metric
    if ES_METRIC == "val_loss":
        improved = (va_loss < best_val_loss - MIN_DELTA)
    elif ES_METRIC == "roc_auc":
        improved = (not math.isnan(va_auc)) and (va_auc > best_auc + MIN_DELTA)
    else:  # "pr_auc"
        improved = (not math.isnan(va_ap)) and (va_ap > best_pr + MIN_DELTA)

    if improved:
        # reset patience & stash best values/weights
        wait = 0
        if ES_METRIC == "val_loss":
            best_val_loss = va_loss
        elif ES_METRIC == "roc_auc":
            best_auc = va_auc
        else:
            best_pr = va_ap

        best_ckpt = {
            "encoder":    copy.deepcopy(encoder.state_dict()),
            "item_model": copy.deepcopy(item_model.state_dict()),
            "ctr_head":   copy.deepcopy(ctr_head.state_dict()),
            # (optional) "opt": copy.deepcopy(opt.state_dict()),
        }
    else:
        wait += 1
        if wait >= PATIENCE:
            print(f"Early stopping at epoch {ep+1} (no improvement for {PATIENCE} epochs).")
            break

# Restore best weights (optional but recommended)
if best_ckpt is not None:
    encoder.load_state_dict(best_ckpt["encoder"])
    item_model.load_state_dict(best_ckpt["item_model"])
    ctr_head.load_state_dict(best_ckpt["ctr_head"])
    print("Restored best checkpoint.")
